AWSTemplateFormatVersion: 2010-09-09
Description: 'Roman number converter web server'

Resources:
 WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

 WebServerHost:
   Type: AWS::EC2::Instance         
   Properties:
      ImageId: ami-08f3d892de259504d
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      Tags:                
        -                        
          Key: Name
          Value: !Sub Web Server of ${AWS::StackName} Stack
      
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            yum update -y
            yum install python3 -y
            yum install pip3 -y
            yum install Flask -y
            yum install git -y
            git clone https://github.com/Ummuhan-web/Clarusway-aws-workshop.git
            python3 clarusway-aws-workshop/hands-on/001-roman-numerals-converter/app.py


Outputs:
  WebsiteURL:
    Value: !Sub 
      - http://${PublicAddress}
      - PublicAddress: !GetAtt WebServerHost.PublicDnsName
    Description: Roman Numerals Converter Application URL